### ISSUE TITLE
Take on miscellaneous tasks other onboarders don't want to do or don't have time for. 

### ISSUE THREAD

**Issue by eliheuer** [eliheuer/gf-project-plan-q3-q4-2023#13]
Nothing is beneath me and I could take on tasks that would free others up for doing higher-level work, automating and documenting as I go. I'm up for the remote work equivalent of sweeping the floors and cleaning the bathrooms.

Updating the `to_production` and `to_sandbox` lists and doing social media are examples of this.

**Comment by davelab6** [comment]
The push lists are critically important, so not floor sweeping, but sure, letting the other folks in the community know you want them to tell you about stuff like this to pass to you is good.
