### ISSUE TITLE
Upgrade and onboard more fonts covering Perso-Arabic/Hebrew/Latin in one unified design

### ISSUE THREAD

**Issue by eliheuer** [eliheuer/gf-project-plan-q3-q4-2023#14]
Rubik is an example of a typeface that covers all these scripts and has been successful because of that. 

I'm uniquely positioned to work on fonts like this due to having at least basic reading skills in all scripts (I'm MUCH better at Arabic than Hebrew). I also have a cultural connection potentially making me uncancellable while working on projects like this.

**Comment by davelab6** [comment]
The upgrading part is out of scope until we've got a very small Q of projects waiting to be onboarded; and onboarding existing AHL fonts is covered already for the agreed in scope of all AL fonts :)

**Comment by eliheuer** [comment]
dup of #2
