### ISSUE TITLE
Create and onboard GF Latin Kernel display font demo repos with Fonta, Runebender, and MFEK

### ISSUE THREAD

**Issue by eliheuer** [eliheuer/gf-project-plan-q3-q4-2023#9]
There are still a lot of people using editors like FontForge and FontCreator. This make the onboarding and collaboration process difficult. 

I will create a few demo fonts using next-gen font editors and promote them on social media. This will help with QA on the new editors and help people get the idea that these editors are approaching a point of usability.

These would cover well-know display font styles that are not in the GF Catolog, like: https://github.com/eliheuer/mebo

![FxaCUWkaUAAVy_R](https://github.com/eliheuer/gf-project-plan-q3-q4-2023/assets/5162664/e9fd5163-dac1-4a28-b800-3362f94b2025)

**Comment by davelab6** [comment]
Since every editor worth its salt will export UFO+DS, if we have a clear onboarding process for UFO+DS, I think this is a lower priority. For now I suggest to keep it open and put it in an "icebox" milestone.
